# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
# .NET Core SDK/Runtime Installer
# Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks.
- task: DotNetCoreInstaller@0
  displayName: Install .NET Core SDK (2.2.203)
  inputs:
    packageType: 'sdk'
    # Dictated by global.json
    version: '2.2.203' 
- script: dotnet restore
  displayName: Restore Dependencies
# Build & Package
- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'Build - ($(buildConfiguration))'
# Run Tests
- task: DotNetCoreCLI@2
  displayName: Run Tests
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build'
# Copy Packages to Artifact Staging
- task: CopyFiles@2
  inputs:
    sourceFolder: src
    contents: |
     **/*.nupkg
     **/*.snupkg
    targetFolder: '$(build.artifactstagingdirectory)'
    flattenFolders: true
- task: PublishBuildArtifacts@1
